demo/urls.py
from django.urls import path
from demo import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views 

urlpatterns = [
    # ///////////////////////////////
    path('myhome/', views.index, name='index'),
    path('post/<int:x>/', views.post, name='post'),
    path('posts/', views.posts, name='posts'),
    path('add/', views.add, name='add'),
    path('products/' ,views.products,name="products"),
    path('product/<p_id>/', views.product, name='product_details'),
    path('add_product/',views.add_product,name="add_product"),
    path('product_del/<p_id>/',views.del_product,name="product_del"),
    path('del_comment/<c_id>/',views.del_comment,name="del_comment"),
    path('product_edit/<p_id>/',views.product_edit,name="product_edit"),
    path('signup/',views.register,name="signup"),
    path('logout/',views.logout_user,name='logout'),
    path('login/',views.login_user,name='login'),
    path("fav/",views.fav,name="fav"),
    path("counter/" ,views.counter ,name="counter")
    # path('posts/',TemplateView.as_view(template_name="products.html"), name='posts')
    # ///////////////////////////////

]

demo1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from demo import views
urlpatterns = [
    path('admin/', admin.site.urls),
    # ///////////////////////////////
    # path('myhome/', views.index, name='index'),
    # path('post/<int:x>/', views.post, name='post_detailes'),
    # ///////////////////////////////
    path("home/",include("demo.urls"))    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

demo/forms.py
from dataclasses import field, fields
from email.policy import default
from logging import PlaceHolder
from pyexpat import model
from tkinter import TRUE, Widget
from django import forms
from django.forms import TextInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from . import models
class AddItemForm(forms.ModelForm):    
    # name = forms.CharField(max_length=100,required=TRUE,widget=forms.TextInput(attrs={'class': "form-control p-4",'placeholder':"name"}))
    # img = forms.ImageField(label='uploade image')
    # color = forms.ChoiceField(choices=models.Colour.choices)
    # price=forms.IntegerField(label="price",help_text="enter price")
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for key, field in self.fields.items():
    #         field.label = ""
    class Meta:
        model=models.item
        fields=("name","img","flavor","price")
        # fields='__all__'
class ProductForm(forms.ModelForm): 
    name=forms.CharField(  max_length=100,required=TRUE,widget=forms.TextInput(attrs={'class': "form-control p-4",'placeholder':"product_name"})) 
    img=forms.ImageField(label='',widget=forms.FileInput(attrs={"aria-describedby":"inputGroupFileAddon04"}))
    size=forms.ChoiceField(widget=forms.Select(attrs={'class': "form-control "}),choices=models.Size.choices,)
    price=forms.DecimalField(widget=forms.TextInput(attrs={'class': "form-control "}))

    class Meta:
        model=models.product
        fields=("name","img","size","price")
        # fields='__all__'
        Widgets={
            'name':TextInput(attrs={'placeholder':'form-control p-4'}),
        }

class UserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1',"password2"]
        # fields='__all__'
class CommentForm(forms.ModelForm):
    title=forms.CharField(max_length=20,widget=forms.TextInput(attrs={'class':"form-control p-4","placeholder":"title",}))
    body=forms.CharField(widget=forms.Textarea(attrs={'class':"form-control p-4","placeholder":"leave your comment","rows":4,"cols":8}))
    class Meta:
        model=models.comment
        # fields=[]
        fields='__all__'

templates/about1.html
{% extends "template.html" %}

{% block about %}
{% load static %}
    <!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <h1 class="section-title position-relative text-center mb-5">Traditional & Delicious Ice Cream Since 1950</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 py-5">
                    <h4 class="font-weight-bold mb-3">About Us</h4>
                    <h5 class="text-muted mb-3">Eos kasd eos dolor vero vero, lorem stet diam rebum. Ipsum amet sed vero dolor sea</h5>
                    <p>Takimata sed vero vero no sit sed, justo clita duo no duo amet et, nonumy kasd sed dolor eos diam lorem eirmod. Amet sit amet amet no. Est nonumy sed labore eirmod sit magna. Erat at est justo sit ut. Labor diam sed ipsum et eirmod</p>
                    <a href="" class="btn btn-secondary mt-2">Learn More</a>
                </div>
                <div class="col-lg-4" style="min-height: 400px;">
                    <div class="position-relative h-100 rounded overflow-hidden">
                        
                        <img class="position-absolute w-100 h-100" src="{%static 'img/about.jpg'%}" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-4 py-5">
                    <h4 class="font-weight-bold mb-3">Our Features</h4>
                    <p>Invidunt lorem justo sanctus clita. Erat lorem labore ea, justo dolor lorem ipsum ut sed eos, ipsum et dolor kasd sit ea justo. Erat justo sed sed diam. Ea et erat ut sed diam sea ipsum est dolor</p>
                    <h5 class="text-muted mb-3"><i class="fa fa-check text-secondary mr-3"></i>Eos kasd eos dolor</h5>
                    <h5 class="text-muted mb-3"><i class="fa fa-check text-secondary mr-3"></i>Eos kasd eos dolor</h5>
                    <h5 class="text-muted mb-3"><i class="fa fa-check text-secondary mr-3"></i>Eos kasd eos dolor</h5>
                    <a href="" class="btn btn-primary mt-2">Learn More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
{% endblock %}

templates/add_item.html
 {% extends "template.html" %}

{% block about %}
{% load static %}
    <!-- About Start -->
    <div class="container-fluid py-5"> 
        
                        <form method="POST" action="" enctype="multipart/form-data" > {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="add" >
                           </form>
                    
    </div>
    <!-- About End -->
{% endblock %} 

templates/add_product.html
{% extends "template.html" %}

{% block about %}
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h1 class="section-title position-relative text-center mb-5">Add new product</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <div class="contact-form bg-light rounded p-5">
                    <div id="success"></div>
{% load static %}
    <!-- About Start -->
    {% comment %} {{request.method}} {% endcomment %}
    
   <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% comment %} {{product_form.as_p}}  {% endcomment %}
    {% for field in product_form %}
    <div>
        <label for="id_img" class="form-label">{{field.label}}</label>
    {{field}}
    <br><br>
    </div>
    {% endfor %}
   <input type="submit"  class="btn btn-primary btn-block py-3 px-5" value="save">
   </form>
   {% for i in product_form.errors %}
   {{ product_form.errors.name }}
   {% endfor %}
    <!-- About End -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/detail.html
{% extends "template.html" %}

{% block about %}
{% load static %}
    

<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card mb-3">
                    <img src="/media_imgs/{{item.img}}"  class="card-img-top" alt="..." height=200px>
                    <div class="card-body">
                      <h5 class="card-title">{{item.name|title}}|{{item.size}}|{{item.price}}</h5>
                      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                  </div>
                
                <hr>
                {% for i in list %}
                <div class="card">
                    <div class="card-body">
                      <h5 class="card-title" style="color:pink">{{ i.title }}</h5>
                      <p class="card-text">{{i.body}}</p>
                      {% if i.user == user %}
                      <a href="{% url 'del_comment' c_id=i.id %}" class=
                      "btn btn-sm btn-danger">delete</a>
                      {% endif %}
                    </div>
                  </div>
                <br>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <form action="" method="POST" style="border: solid 2px pink ; border-raduis:10;border-radius: 10px ; padding:20px;width:80%;margin-left:50px" >
                    {% csrf_token %}
                      {{form.title}}
                    <br>
                    {{form.body}} 
                    {% comment %} {{form.product.value}} {% endcomment %}
                     {% comment %} {{form.as_p}}  {% endcomment %}
                     <br>
                <input type="submit" class="btn btn-primary btn-block py-3 px-5">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/editform.html
{% extends "template.html" %}

{% block about %}
{% load static %}
    <!-- About Start -->
    {% comment %} {{request.method}} {% endcomment %}
   <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
   {% comment %} Name: <input name="name"  value="{{item.name}}" type="text">
   <br>
   price: <input name="price" type="number" value="{{item.price}}">
   <br>
  Size: <select name="size">
    <option value="small">small</option>
    <option value="medium">medium</option>
    <option value="larg">larg</option>
   </select>
   <br>
   Image: <input name="img" type="file">
   <br>
    {% endcomment %}
   {{form.as_p}}
   <input type="submit" value="save">
   </form>
    <!-- About End -->
{% endblock %}

templates/galary.html
{% extends "template.html" %}

{% block about %}
{% load static %}
    <!-- About Start -->
    {% comment %} {{items}} {% endcomment %}

    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                   
                    <h1 class="section-title position-relative text-center mb-5">Best Prices We Offer For Ice Cream Lovers</h1>
                </div>
            </div>
            <div class="row">
                {% for item in items %}
                <div class="col-lg-3 col-md-6 mb-4 pb-2">
                    <div class="product-item d-flex flex-column align-items-center text-center bg-light rounded py-5 px-3">
                        <div class="bg-primary mt-n5 py-3" style="width: 80px;">
                            <h4 class="font-weight-bold text-white mb-0">${{item.price}}</h4>
                        </div>
                        <div class="position-relative bg-primary rounded-circle mt-n3 mb-4 p-3" style="width: 150px; height: 150px;">
                            <img class="rounded-circle w-100 h-100" src="/media_imgs/{{item.img}}" style="object-fit: cover;">
                        </div>
                        <h5 class="font-weight-bold mb-4">{{item.name}} </h5>
                        <a  href={% url "fav" %}><i class="fa fa-heart" style="font-size:48px;color:red"></i>
                        </a>
                        <a href="{% url 'product_details' p_id=item.id %}" class="btn btn-sm btn-secondary">details</a>
                        {% if user.is_superuser %} <a href="{% url 'product_del' p_id=item.id %}" class="btn btn-sm btn-danger">delete</a>
                        <a href="{% url 'product_edit' p_id=item.id %}" class="btn btn-sm btn-secondary">edit</a> {% endif %}
                    </div>
                </div>
                 {% endfor %}
            
            </div>
        </div>
    </div>
    <!-- About End -->
{% endblock %}

templates/home.html
{% extends "template.html" %}

{% block about %}
{% load static %}
    <!-- About Start -->
   
    <!-- About End -->
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body>
    <h1>my first html page</h1>
    {{request.GET}}
    <p>hey {{colors}}</p>
    {% for i in colors  %}
    {%if i == "wheit"%}
    <p>wrong choice</p>
    {%else%}
    <p>{{i}}</p>
    {%endif%}
    {%endfor%}

    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
            {% for i in colors  %}
          <li class="list-group-item">{{i}}</li>
          {%endfor%}
        </ul>
      </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Sign up / Login Form</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'style.css'%}">

</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html>
<head>
	<title>Slide Navbar</title>
	<link rel="stylesheet" type="text/css" href="slide navbar style.css">
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form action="" method="post">
                    {% csrf_token %}
					<label for="chk" aria-hidden="true">Login</label>
					<input type="text" name="username" placeholder="Username" required="">
					{% comment %} <input type="email" name="email" placeholder="Email" required=""> {% endcomment %}
					<input type="password" name="password" placeholder="Password" required="">
					{% if messages %}
                   <ul class="messages">
                 {% for message in messages %}
             <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
               {% endfor %}
                </ul>
               {% endif %}
                    <button >Login</button>
				</form>
			</div>

			{% comment %} <div class="login">
				<form>
					<label for="chk" aria-hidden="true">Login</label>
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Login</button>
				</form>
			</div> {% endcomment %}
	</div>
</body>
</html>
<!-- partial -->
  
</body>
</html>

templates/products.html
{% extends "template.html" %}
{% block header %}   
<!-- Header Start -->
<div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
    <div class="container text-center py-5">
        <h1 class="text-white display-3 mt-lg-5">products</h1>
        
    </div>
</div>
<!-- Header End -->
{% endblock %}
{% block about %}

       <!-- Products Start -->
       {% load static %}
       <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h1 class="section-title position-relative text-center mb-5">Best Prices We Offer For Ice Cream Lovers</h1>
                </div>
            </div>
            <div class="row">
                {% for item in items %}
                <div class="col-lg-3 col-md-6 mb-4 pb-2">
                    <div class="product-item d-flex flex-column align-items-center text-center bg-light rounded py-5 px-3">
                        <div class="bg-primary mt-n5 py-3" style="width: 80px;">
                            <h4 class="font-weight-bold text-white mb-0">{{item.price}}</h4>
                        </div>
                        <div class="position-relative bg-primary rounded-circle mt-n3 mb-4 p-3" style="width: 150px; height: 150px;">
                            <img class="rounded-circle w-100 h-100" src="/media_imgs/{{item.img}}" style="object-fit: cover;">
                        </div>
                        <h5 class="font-weight-bold mb-4">{{item.name}}</h5>
                        <a href="{% url 'product_del' p_id=item.id %}" class="btn btn-sm btn-secondary">delete</a>
                    </div>
                </div>
                {% empty %}
                <h1> no products </h1>
               {% endfor %}
            </div>
        </div>
       </div>
    <!-- Products End -->
{% endblock %}

templates/register.html
{% extends "template.html" %}

{% block about %}
{% load static %}
 <form action="" method="post">
    {% csrf_token %} 
     {% for field in form %}
  {{field.label}} : {{field}}
  <br><br>
  {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form> 
 {{form.errors}}
 
{% endblock %}

templates/signup.html
{% extends "template.html" %}

{% block about %}
{% load static %}
    <!-- About Start -->
    <div class="container-fluid py-5"> 
        
                        <form method="POST" action="" enctype="multipart/form-data" > {% csrf_token %}
                            {% for field in form%}
                            <br>
                            {{field.label}} :{{field}}
                           
                            {% endfor %}
                            {% comment %} {{ form.as_p }} {% endcomment %}
                            
                            <input type="submit" value="add" >
                           </form>
                    
    </div>
    <!-- About End -->
{% endblock %} 

templates/template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>iCREAM - Ice Cream Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    {% load static %}
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid bg-primary py-3 d-none d-md-block">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white pr-3" href="">FAQs</a>
                        <span class="text-white">|</span>
                        <a class="text-white px-3" href="">Help</a>
                        <span class="text-white">|</span>
                        <a class="text-white pl-3" href="">Support</a>
                    </div>
                </div>
                <div class="col-md-6 text-center text-lg-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-white px-3" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-white px-3" href="">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-white pl-3" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

{% block navbar %}
    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0">
        <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
            <nav class="navbar navbar-expand-lg bg-white navbar-light shadow p-lg-0">
                <a href="index.html" class="navbar-brand d-block d-lg-none">
                    <h1 class="m-0 display-4 text-primary"><span class="text-secondary">i</span>CREAM</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto py-0">
                        <span class="nav-item nav-link">{% if request.user.id != None %}
                            {{user}}
                            {% endif %}
                        </span>
                    
                    {% if user.is_authenticated %}    <a href="{% url 'logout' %}" class="nav-item nav-link active">Logout</a>{% else %}
                    <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
                    {% endif %}
                        {% comment %} <a href="{% url 'posts' %}" class="nav-item nav-link">Product</a> {% endcomment %}
                    </div>
                    <a href="index.html" class="navbar-brand mx-5 d-none d-lg-block">
                        
                        <h1 class="m-0 display-4 text-primary"><span class="text-secondary">i</span>CREAM</h1>
                    </a>
                    <div class="navbar-nav mr-auto py-0">
                     
                        
                        <a href="{% url 'products' %}" class="nav-item nav-link">Gallery</a>
                        {% if user.is_superuser %} <a href="{% url 'add_product' %}" class="nav-item nav-link">add recpie</a>{% endif %}
                        <a href="" class="nav-item nav-link"><p><i class="fa fa-heart" style="font-size:25px;color:red"></i><span style="position:relative; top:-18px;left:-4px" class="badge badge-secondary"> {{ request.session.fav }} </span></p></a>
                    
     
                </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->
    {% endblock %}
    {% block header %}   
    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
        <div class="container text-center py-5">
         
            <h1 class="text-white display-3 mt-lg-5">About</h1>
            <div class="d-inline-flex align-items-center text-white">
                <p class="m-0"><a class="text-white" href="">Home</a></p>
                <i class="fa fa-circle px-3"></i>
                <p class="m-0">About</p>
            </div>
        </div>
    </div>
    <!-- Header End -->
    {% endblock %}
{% block about %}
 
{% endblock %}


    <!-- Footer Start -->
    <div class="container-fluid footer bg-light py-5" style="margin-top: 90px;">
        <div class="container text-center py-5">
            <div class="row">
                <div class="col-12 mb-4">
                    <a href="index.html" class="navbar-brand m-0">
                        <h1 class="m-0 mt-n2 display-4 text-primary"><span class="text-secondary">i</span>CREAM</h1>
                    </a>
                </div>
                <div class="col-12 mb-4">
                    <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-secondary btn-social" href="#"><i class="fab fa-instagram"></i></a>
                </div>
                <div class="col-12 mt-2 mb-4">
                    <div class="row">
                        <div class="col-sm-6 text-center text-sm-right border-right mb-3 mb-sm-0">
                            <h5 class="font-weight-bold mb-2">Get In Touch</h5>
                            <p class="mb-2">123 Street, New York, USA</p>
                            <p class="mb-0">+012 345 67890</p>
                        </div>
                        <div class="col-sm-6 text-center text-sm-left">
                            <h5 class="font-weight-bold mb-2">Opening Hours</h5>
                            <p class="mb-2">Mon – Sat, 8AM – 5PM</p>
                            <p class="mb-0">Sunday: Closed</p>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <p class="m-0">&copy; <a href="#">Domain</a>. All Rights Reserved. Designed by <a href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-secondary px-2 back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>